###  baseURL = 'https://www.luminaria.it/'
baseURL = "https://ilum75IDB.github.io/www.luminaria.it/"
title = "Ivan Luminaria"
theme = "congo"
languageCode = 'it'

defaultContentLanguage = "it"
defaultContentLanguageInSubdir = true
